//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PageResource.PageResource", typeof(PageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account lock.
        /// </summary>
        public static string AccountLock {
            get {
                return ResourceManager.GetString("AccountLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic logout.
        /// </summary>
        public static string AutomaticLogout {
            get {
                return ResourceManager.GetString("AutomaticLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betting limits.
        /// </summary>
        public static string BettingLimits {
            get {
                return ResourceManager.GetString("BettingLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASINO.
        /// </summary>
        public static string Casino {
            get {
                return ResourceManager.GetString("Casino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address change.
        /// </summary>
        public static string EmailAddressChanege {
            get {
                return ResourceManager.GetString("EmailAddressChanege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgottenPassword {
            get {
                return ResourceManager.GetString("ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        public static string ForgottenPasswordHeading {
            get {
                return ResourceManager.GetString("ForgottenPasswordHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your username?.
        /// </summary>
        public static string ForgottenUsername {
            get {
                return ResourceManager.GetString("ForgottenUsername", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgotten username.
        /// </summary>
        public static string ForgottenUsernameHeading {
            get {
                return ResourceManager.GetString("ForgottenUsernameHeading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LIVE BETTING.
        /// </summary>
        public static string LiveBetting {
            get {
                return ResourceManager.GetString("LiveBetting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LIVE CASSIONO.
        /// </summary>
        public static string LiveCasino {
            get {
                return ResourceManager.GetString("LiveCasino", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login successfull.
        /// </summary>
        public static string LoginSuccessfull {
            get {
                return ResourceManager.GetString("LoginSuccessfull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LOG OFF.
        /// </summary>
        public static string LogOffButton {
            get {
                return ResourceManager.GetString("LogOffButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password change.
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Requirements for valid password:
        ///must consist of at least 5, at most 40 characters
        ///cannot contain spaces
        ///cannot be similar to or contain other personal data (e.g. first name, last name, username, etc.)
        ///allowed special characters: !#$()@?{}|*+,^.-+&amp;=%_:;~
        ///Tips for a secure password:
        ///should consist of at least 8 characters
        ///should contain at least one lowercase letter (a-z), one uppercase letter (A-Z), one number (0-9) and one special character
        ///longer and more complex passwords are more secure
        ///select  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PasswordChangeRequirements {
            get {
                return ResourceManager.GetString("PasswordChangeRequirements", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SPORTS BETTING.
        /// </summary>
        public static string SportsBetting {
            get {
                return ResourceManager.GetString("SportsBetting", resourceCulture);
            }
        }
    }
}
