//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErrorMessages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account already blocked till.
        /// </summary>
        public static string AccountAlreadyBlocked {
            get {
                return ResourceManager.GetString("AccountAlreadyBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account temporarily blocked.
        /// </summary>
        public static string AccountBlocked {
            get {
                return ResourceManager.GetString("AccountBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account blocked till.
        /// </summary>
        public static string AccountBlockedTill {
            get {
                return ResourceManager.GetString("AccountBlockedTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account permanently blocked.
        /// </summary>
        public static string AccountPermaBlocked {
            get {
                return ResourceManager.GetString("AccountPermaBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log me out automatically after.
        /// </summary>
        public static string AutoLogOff {
            get {
                return ResourceManager.GetString("AutoLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic log off required.
        /// </summary>
        public static string AutoLogOffRequired {
            get {
                return ResourceManager.GetString("AutoLogOffRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your timeout period has expired.
        /// </summary>
        public static string AutoOdjavaBody {
            get {
                return ResourceManager.GetString("AutoOdjavaBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic timeout.
        /// </summary>
        public static string AutoOdjavaHead {
            get {
                return ResourceManager.GetString("AutoOdjavaHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betting limit required.
        /// </summary>
        public static string BettingLimitRequired {
            get {
                return ResourceManager.GetString("BettingLimitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betting timeout.
        /// </summary>
        public static string BettingTimeout {
            get {
                return ResourceManager.GetString("BettingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday required.
        /// </summary>
        public static string BirthdayRequired {
            get {
                return ResourceManager.GetString("BirthdayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha is not valid.
        /// </summary>
        public static string CaptchaNotValid {
            get {
                return ResourceManager.GetString("CaptchaNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the following link to confirm your new email address .
        /// </summary>
        public static string ChangeEmailBody {
            get {
                return ResourceManager.GetString("ChangeEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email change confirmation link.
        /// </summary>
        public static string ChangeEmailHead {
            get {
                return ResourceManager.GetString("ChangeEmailHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City required.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email required.
        /// </summary>
        public static string ConfirmEmailRequired {
            get {
                return ResourceManager.GetString("ConfirmEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password required.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country required.
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address and birthdate do not match..
        /// </summary>
        public static string EmailAndBirthdateError {
            get {
                return ResourceManager.GetString("EmailAndBirthdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address changes. New email address is .
        /// </summary>
        public static string EmailChanged {
            get {
                return ResourceManager.GetString("EmailChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address successfully confirmed.
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already taken.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email do not match.
        /// </summary>
        public static string EmailMatch {
            get {
                return ResourceManager.GetString("EmailMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not confirmed.
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user with entered email address..
        /// </summary>
        public static string EmailNotExist {
            get {
                return ResourceManager.GetString("EmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent to .
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation required.
        /// </summary>
        public static string ExplanationRequired {
            get {
                return ResourceManager.GetString("ExplanationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House number.
        /// </summary>
        public static string HouseNumber {
            get {
                return ResourceManager.GetString("HouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language required.
        /// </summary>
        public static string LanguageRequired {
            get {
                return ResourceManager.GetString("LanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not be similar to first name, second name or username..
        /// </summary>
        public static string LevenhsteinError {
            get {
                return ResourceManager.GetString("LevenhsteinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link not valid.
        /// </summary>
        public static string LinkNotValid {
            get {
                return ResourceManager.GetString("LinkNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link is valid for 30 minutes..
        /// </summary>
        public static string LinkValidity {
            get {
                return ResourceManager.GetString("LinkValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock duration.
        /// </summary>
        public static string LockDuration {
            get {
                return ResourceManager.GetString("LockDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock duration required.
        /// </summary>
        public static string LockDurationRequired {
            get {
                return ResourceManager.GetString("LockDurationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock reason.
        /// </summary>
        public static string LockReason {
            get {
                return ResourceManager.GetString("LockReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock reason required.
        /// </summary>
        public static string LockReasonRequired {
            get {
                return ResourceManager.GetString("LockReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfull.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone number.
        /// </summary>
        public static string MobilePhoneNumber {
            get {
                return ResourceManager.GetString("MobilePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfuly changed.
        /// </summary>
        public static string PasswordChangeSuccess {
            get {
                return ResourceManager.GetString("PasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 8 characters of which one is lowercase one uppercase one number and one special symbol.
        /// </summary>
        public static string PasswordExpression {
            get {
                return ResourceManager.GetString("PasswordExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must consist of at least 8 and at moast 40 characters.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password do not match.
        /// </summary>
        public static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the link to reset your password.
        /// </summary>
        public static string PasswordResetLinkBody {
            get {
                return ResourceManager.GetString("PasswordResetLinkBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset link.
        /// </summary>
        public static string PasswordResetLinkHead {
            get {
                return ResourceManager.GetString("PasswordResetLinkHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset link is sent to .
        /// </summary>
        public static string ResetLinkSent {
            get {
                return ResourceManager.GetString("ResetLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password can&apos;t be same as your old password..
        /// </summary>
        public static string SamePassError {
            get {
                return ResourceManager.GetString("SamePassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second name.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second name required.
        /// </summary>
        public static string SecondNameRequired {
            get {
                return ResourceManager.GetString("SecondNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error!.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session expired!.
        /// </summary>
        public static string SessionTimeOutAlert {
            get {
                return ResourceManager.GetString("SessionTimeOutAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session expires in 20 seconds!.
        /// </summary>
        public static string SessionTimeOutBody {
            get {
                return ResourceManager.GetString("SessionTimeOutBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is expireing.
        /// </summary>
        public static string SessionTimeOutHead {
            get {
                return ResourceManager.GetString("SessionTimeOutHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street name.
        /// </summary>
        public static string StreetName {
            get {
                return ResourceManager.GetString("StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street name required.
        /// </summary>
        public static string StreetRequired {
            get {
                return ResourceManager.GetString("StreetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title required.
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and birthdate do not match..
        /// </summary>
        public static string UsernameAndBirthddateError {
            get {
                return ResourceManager.GetString("UsernameAndBirthddateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already taken.
        /// </summary>
        public static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between 6 and 20 alfanumeric characters including - and _.
        /// </summary>
        public static string UsernameExpression {
            get {
                return ResourceManager.GetString("UsernameExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username is:.
        /// </summary>
        public static string UsernameMail {
            get {
                return ResourceManager.GetString("UsernameMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username sent to .
        /// </summary>
        public static string UsernameMailSent {
            get {
                return ResourceManager.GetString("UsernameMailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user with entered username..
        /// </summary>
        public static string UsernameNotExist {
            get {
                return ResourceManager.GetString("UsernameNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username.
        /// </summary>
        public static string WrongUsername {
            get {
                return ResourceManager.GetString("WrongUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP code required.
        /// </summary>
        public static string ZipRequired {
            get {
                return ResourceManager.GetString("ZipRequired", resourceCulture);
            }
        }
    }
}
